# Generated by Django 3.0.5 on 2021-05-23 12:46

from django.db import migrations


def create_data(apps, schema_editor):
    Weather = apps.get_model('weather', 'Weather')
    Weather(name="sunny", weather_status="18.8").save()


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather'),
    ]

    operations = [
    ]
